labels: ["kind/documentation"]
body:
  - type: markdown
    attributes:
      value: |
        #### Note
        Feel free to create a docs report if something doesn't work as expected or is unclear in the documentation.
        Please ensure that you're not asking a duplicate question by searching the [issues](https://github.com/RoKrish14/sig-security/issues) beforehand.
  - type: textarea
    attributes:
      label: Description
      description: Briefly describe the what has been unclear in the existing documentation
    validations:
      required: true
  - type: textarea
    attributes:
      label: Suggestions
      description: What would you like to have added or changed in the documentation?
    validations:
      required: true
