blank_issues_enabled: false
contact_links:
  - name: Ask the community for help
    url: https://github.com/RoKrish14/sig-security/discussions/categories/q-a
    about: Ask questions and discuss with other community members

  - name: Enhance documentation
    url: https://github.com/RoKrish14/sig-security/discussions/categories/documentation
    about: Make suggestions to the documentation
