name: Run KICS scan and upload SARIF

on:
  push:
    branches: main
    paths-ignore:
      - "**/*.md"
      - "**/*.txt"
  schedule:
    - cron: "0 0 * * *" # Once a day
  workflow_dispatch:

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run KICS Scan with SARIF result
        uses: checkmarx/kics-github-action@v1.7.0
        with:
          # Scanning directory .
          path: "."
          # When provided with a directory on output_path
          # it will generate the specified reports file named 'results.{extension}'
          # in this example it will generate: kicsResults/results.sarif
          output_path: kicsResults/
          output_formats: "sarif"
          # If you want KICS to ignore the results and return exit status code 0 unless a KICS engine error happens
          ignore_on_exit: results
          # Exclude paths or files from scan
          # exclude_paths: "terraform/gcp/big_data.tf,terraform/azure"
          # Exclude accepted queries from the build
          # exclude_queries: 0437633b-daa6-4bbc-8526-c0d2443b946e
          # No secret scanning
          disable_secrets: true

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: kicsResults/results.sarif
