name: "Run Trivy scan and upload SARIF"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Once a day

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      # Pull image from Docker Hub and run Trivy vulnerability scanner
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.12.0
        with:
          image-ref: "tractusx/irs-api:latest"
          format: "sarif"
          output: "trivy-results.sarif"
          vuln-type: "os,library"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "trivy-results.sarif"
